[package]
name = "fls"
version = "0.1.0"
authors = ["Ben Kimock <kimockb@gmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
veneer = {git = "https://github.com/saethlin/veneer"}
libc = "0.2"
itoa = {version = "0.4", default-features = false}
unicode-segmentation = "1.3"

[profile.dev]
opt-level = 1
panic = "abort"

[profile.release]
debug = 1
lto = "fat"
panic = "abort"
